Application:
  Organizations: null
Capabilities:
  Application:
    V1_1: true
  Global:
    V1_1: true
  Orderer:
    V1_1: true
Orderer:
  Addresses:
  - orderer0_orange_com:7050
  - orderer1_orange_com:8050
  BatchSize:
    AbsoluteMaxBytes: 99 MB
    MaxMessageCount: 10
    PreferredMaxBytes: 512 KB
  BatchTimeout: 2s
  Capabilities:
    V1_1: true
  Kafka:
    Brokers:
    - 127.0.0.1:9092
  OrdererType: solo
  Organizations: null
Organizations:
- ID: OrdererMSP
  MSPDir: crypto-config/ordererOrganizations/orange_com/msp
  Name: OrdererOrg
- AnchorPeers:
  - Host: peer0_org1_orange_com
    Port: 7051
  ID: org1MSP
  MSPDir: crypto-config/peerOrganizations/org1_orange_com/msp
  Name: org1MSP
- AnchorPeers:
  - Host: peer0_org2_orange_com
    Port: 7051
  ID: org2MSP
  MSPDir: crypto-config/peerOrganizations/org2_orange_com/msp
  Name: org2MSP
Profiles:
  OrgsChannel:
    Application:
      Organizations:
      - AnchorPeers:
        - Host: peer0_org1_orange_com
          Port: 7051
        ID: org1MSP
        MSPDir: crypto-config/peerOrganizations/org1_orange_com/msp
        Name: org1MSP
      - AnchorPeers:
        - Host: peer0_org2_orange_com
          Port: 7051
        ID: org2MSP
        MSPDir: crypto-config/peerOrganizations/org2_orange_com/msp
        Name: org2MSP
    Consortium: SampleConsortium
  OrgsOrdererGenesis:
    Capabilities:
      V1_1: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - AnchorPeers:
          - Host: peer0_org1_orange_com
            Port: 7051
          ID: org1MSP
          MSPDir: crypto-config/peerOrganizations/org1_orange_com/msp
          Name: org1MSP
        - AnchorPeers:
          - Host: peer0_org2_orange_com
            Port: 7051
          ID: org2MSP
          MSPDir: crypto-config/peerOrganizations/org2_orange_com/msp
          Name: org2MSP
    Orderer:
      Addresses:
      - orderer0_orange_com:7050
      - orderer1_orange_com:8050
      BatchSize:
        AbsoluteMaxBytes: 99 MB
        MaxMessageCount: 10
        PreferredMaxBytes: 512 KB
      BatchTimeout: 2s
      Capabilities:
        V1_1: true
      Kafka:
        Brokers:
        - 127.0.0.1:9092
      OrdererType: solo
      Organizations:
      - ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/orange_com/msp
        Name: OrdererOrg
