networks:
  sample: {}
services:
  kafka0_orange_com:
    container_name: kafka0_orange_com
    depends_on:
    - zookeeper0_orange_com
    - zookeeper1_orange_com
    - zookeeper2.example.com
    environment:
      KAFKA_BROKER_ID: '0'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
      KAFKA_MESSAGE_MAX_BYTES: '103809024'
      KAFKA_MIN_INSYNC_REPLICAS: '2'
      KAFKA_REPLICA_FETCH_MAX_BYTES: '103809024'
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0_orange_com:2181,zookeeper1_orange_com:2181,zookeeper2.example.com:2181
    image: hyperledger/fabric-kafka
    networks:
      sample: null
    ports:
    - 9092:9092/tcp
    - 9093:9093/tcp
    restart: always
  kafka1_orange_com:
    container_name: kafka1_orange_com
    depends_on:
    - zookeeper0_orange_com
    - zookeeper1_orange_com
    - zookeeper2.example.com
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
      KAFKA_MESSAGE_MAX_BYTES: '103809024'
      KAFKA_MIN_INSYNC_REPLICAS: '2'
      KAFKA_REPLICA_FETCH_MAX_BYTES: '103809024'
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0_orange_com:2181,zookeeper1_orange_com:2181,zookeeper2.example.com:2181
    image: hyperledger/fabric-kafka
    networks:
      sample: null
    ports:
    - 10092:9092/tcp
    - 10093:9093/tcp
    restart: always
  kafka2_orange_com:
    container_name: kafka2_orange_com
    depends_on:
    - zookeeper0_orange_com
    - zookeeper1_orange_com
    - zookeeper2.example.com
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
      KAFKA_MESSAGE_MAX_BYTES: '103809024'
      KAFKA_MIN_INSYNC_REPLICAS: '2'
      KAFKA_REPLICA_FETCH_MAX_BYTES: '103809024'
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0_orange_com:2181,zookeeper1_orange_com:2181,zookeeper2.example.com:2181
    image: hyperledger/fabric-kafka
    networks:
      sample: null
    ports:
    - 11092:9092/tcp
    - 11093:9093/tcp
    restart: always
  kafka3_orange_com:
    container_name: kafka3_orange_com
    depends_on:
    - zookeeper0_orange_com
    - zookeeper1_orange_com
    - zookeeper2.example.com
    environment:
      KAFKA_BROKER_ID: '3'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
      KAFKA_MESSAGE_MAX_BYTES: '103809024'
      KAFKA_MIN_INSYNC_REPLICAS: '2'
      KAFKA_REPLICA_FETCH_MAX_BYTES: '103809024'
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0_orange_com:2181,zookeeper1_orange_com:2181,zookeeper2.example.com:2181
    image: hyperledger/fabric-kafka
    networks:
      sample: null
    ports:
    - 12092:9092/tcp
    - 12093:9093/tcp
    restart: always
  zookeeper0_orange_com:
    container_name: zookeeper0_orange_com
    environment:
      ZOO_MY_ID: '1'
      ZOO_SERVERS: server.1=zookeeper0_orange_com:2888:3888 server.2=zookeeper1_orange_com:2888:3888
        server.3=zookeeper2.example.com:2888:3888
    image: hyperledger/fabric-zookeeper
    networks:
      sample: null
    ports:
    - 2181:2181/tcp
    - 2888:2888/tcp
    - 3888:3888/tcp
    restart: always
  zookeeper1_orange_com:
    container_name: zookeeper1_orange_com
    environment:
      ZOO_MY_ID: '2'
      ZOO_SERVERS: server.1=zookeeper0_orange_com:2888:3888 server.2=zookeeper1_orange_com:2888:3888
        server.3=zookeeper2.example.com:2888:3888
    image: hyperledger/fabric-zookeeper
    networks:
      sample: null
    ports:
    - 12181:2181/tcp
    - 12888:2888/tcp
    - 13888:3888/tcp
    restart: always
  zookeeper2.example.com:
    container_name: zookeeper2.example.com
    environment:
      ZOO_MY_ID: '3'
      ZOO_SERVERS: server.1=zookeeper0_orange_com:2888:3888 server.2=zookeeper1_orange_com:2888:3888
        server.3=zookeeper2.example.com:2888:3888
    image: hyperledger/fabric-zookeeper
    networks:
      sample: null
    ports:
    - 22181:2181/tcp
    - 22888:2888/tcp
    - 23888:3888/tcp
    restart: always
  ca_peerOrg1:
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca_peerOrg1-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key_sk -b admin:PwD4AdminCA
      -d'
    environment:
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_CA_NAME: ca_peerOrg1
      FABRIC_CA_SERVER_TLS_CERTFILE: /etc/hyperledger/fabric-ca-server-config/ca_peerOrg1-cert.pem
      FABRIC_CA_SERVER_TLS_ENABLED: "True"
      FABRIC_CA_SERVER_TLS_KEYFILE: /etc/hyperledger/fabric-ca-server-config/key_sk
    image: hyperledger/fabric-ca:x86_64-1.1.0
    networks:
      sample: null
    ports:
    - 7054:7054/tcp
    volumes:
    - ${SNGV_DIR}/crypto-config/peerOrganizations/org1_orange_com/ca:/etc/hyperledger/fabric-ca-server-config:rw
  cli:
    deploy:
      restart_policy:
        condition: none
        delay: 60s
    command: /bin/bash -c './scripts/init.sh;'
    depends_on:
    - ca_peerOrg1
    - orderer_orange_com
    - peer0_org1_orange_com
    environment:
      CORE_LOGGING_LEVEL: DEBUG
      CORE_PEER_ADDRESS: peer0_org1_orange_com:7051
      CORE_PEER_ID: cli
      CORE_PEER_LOCALMSPID: Org1MSP
      CORE_PEER_MSPCONFIGPATH: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/users/Admin@org1_orange_com/msp
      CORE_PEER_TLS_CERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls/server.crt
      CORE_PEER_TLS_ENABLED: "True"
      CORE_PEER_TLS_KEY_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls/ca.crt
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      GOPATH: /opt/gopath
    hostname: fabric-cli
    image: hyperledger/fabric-tools:x86_64-1.1.0
    links:
    - orderer_orange_com
    - peer0_org1_orange_com
    - ca_peerOrg1
    networks:
      sample: null
    ports:
    - 5050:5050/tcp
    stdin_open: true
    tty: true
    volumes:
    - /var/run:/host/var/run:rw
    - ${SNGV_DIR}/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode:rw
    - ${SNGV_DIR}/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto:rw
    - ${SNGV_DIR}/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts:rw
    - ${SNGV_DIR}/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  couchdb0:
    environment:
      COUCHDB_PASSWORD: couchdb_pwd0
      COUCHDB_USER: couchdb_user0
    image: hyperledger/fabric-couchdb
    networks:
      sample: null
    ports:
    - 5984:5984/tcp
  orderer_orange_com:
    command: orderer
    environment:
      ORDERER_KAFKA_RETRY_SHORTINTERVAL: 1s
      ORDERER_KAFKA_RETRY_SHORTTOTAL: 30s
      ORDERER_KAFKA_VERBOSE: "true"
      ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/orderer.genesis.block
      ORDERER_GENERAL_GENESISMETHOD: file
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
      ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_LOGLEVEL: debug
      ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ENABLED: "True"
      ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    networks:
      sample: null
    ports:
    - 7050:7050/tcp
    volumes:
    - ${SNGV_DIR}/crypto-config/ordererOrganizations/orange_com/orderers/orderer_orange_com/msp:/var/hyperledger/orderer/msp:rw
    - ${SNGV_DIR}/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block:rw
    - ${SNGV_DIR}/crypto-config/ordererOrganizations/orange_com/orderers/orderer_orange_com/tls:/var/hyperledger/orderer/tls:rw
    - orderer_orange_com:/var/hyperledger/production/orderer:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    depends_on:
    - kafka0_orange_com
    - kafka1_orange_com
    - kafka2_orange_com
    - kafka3_orange_com
  peer0_org1_orange_com:
    command: peer node start
    depends_on:
    - couchdb0
    environment:
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: couchdb0:5984
      CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: couchdb_pwd0
      CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: couchdb_user0
      CORE_LEDGER_STATE_STATEDATABASE: CouchDB
      CORE_LOGGING_LEVEL: DEBUG
      CORE_PEER_ADDRESS: peer0_org1_orange_com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0_org1_orange_com:7051
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_ID: peer0_org1_orange_com
      CORE_PEER_LOCALMSPID: Org1MSP
      CORE_PEER_PROFILE_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_ENABLED: "True"
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: project1_sample
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:x86_64-1.1.0
    networks:
      sample: null
    ports:
    - 7051:7051/tcp
    - 7053:7053/tcp
    volumes:
    - ${SNGV_DIR}/crypto-config/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/msp:/etc/hyperledger/fabric/msp:rw
    - ${SNGV_DIR}/crypto-config/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer0_org1_orange_com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
version: '3.0'
volumes:
  orderer_orange_com: {}
  peer0_org1_orange_com: {}
