networks:
  sample: null
services:
  ca_peerOrg1:
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca_peerOrg1-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key_sk -b admin:PwD4AdminCA
      -d'
    environment:
    - 'TZ: UTC'
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca_peerOrg1
    - FABRIC_CA_SERVER_TLS_ENABLED=True
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca_peerOrg1-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key_sk
    image: hyperledger/fabric-ca:x86_64-1.1.0
    networks: &id002
    - sample
    ports:
    - 7054:7054
    volumes:
    - ${COMPOSE_PROJECT_PATH}/crypto-config/peerOrganizations/org1_orange_com/ca/:/etc/hyperledger/fabric-ca-server-config
  cli:
    command: /bin/bash -c './scripts/init.sh;'
    depends_on: &id001
    - orderer_orange_com
    - peer0_org1_orange_com
    - ca_peerOrg1
    environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=cli
    - 'TZ: UTC'
    - CORE_PEER_ADDRESS=peer0_org1_orange_com:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_TLS_ENABLED=True
    - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/peers/peer0_org1_orange_com/tls/ca.crt
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1_orange_com/users/Admin@org1_orange_com/msp
    hostname: fabric-cli
    image: hyperledger/fabric-tools:x86_64-1.1.0
    links: *id001
    networks: *id002
    ports:
    - 5050:5050
    stdin_open: true
    tty: true
    volumes:
    - /var/run/:/host/var/run/
    - ${COMPOSE_PROJECT_PATH}/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode/
    - ${COMPOSE_PROJECT_PATH}/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    - ${COMPOSE_PROJECT_PATH}/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    - ${COMPOSE_PROJECT_PATH}/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  couchdb0:
    environment:
    - COUCHDB_USER=couchdb_user0
    - COUCHDB_PASSWORD=couchdb_pwd0
    image: hyperledger/fabric-couchdb
    networks: *id002
    ports:
    - 5984:5984
  orderer_orange_com:
    extends:
      file: docker-compose-base.yaml
      service: orderer_orange_com
    networks: &id003
    - sample
  peer0_org1_orange_com:
    depends_on:
    - couchdb0
    environment:
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - 'TZ: UTC'
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb_user0
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb_pwd0
    extends:
      file: docker-compose-base.yaml
      service: peer0_org1_orange_com
    networks: *id003
version: '2'
volumes:
  orderer_orange_com: null
  peer0_org1_orange_com: null
